"""empty message

Revision ID: 502e77f046bb
Revises: 
Create Date: 2020-02-23 10:09:39.907907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502e77f046bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('driver_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drivers')
    # ### end Alembic commands ###
