"""empty message

Revision ID: 50fc31115a21
Revises: d5ceee0eaff1
Create Date: 2020-03-08 19:04:42.124205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50fc31115a21'
down_revision = 'd5ceee0eaff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=128), nullable=True))
    op.drop_column('users', 'email_adress')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_adress', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
